### ISSUE TITLE
Sort report rules/items by impact

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#11]
Need to implement sorting in Desktop/Mobile results – the bigger the impact, the higher it's in the results table (see pics below)

Current:
<img width="1717" alt="current_state" src="https://cloud.githubusercontent.com/assets/2503802/13616619/8a3e2ff2-e52f-11e5-8dc6-7ec892e07f5e.png">

Proposal:
<img width="1720" alt="proposed" src="https://cloud.githubusercontent.com/assets/2503802/13616618/8a3d8f8e-e52f-11e5-8b9c-5c35afdc8e9d.png">

**Comment by vpodk** [comment]
Sorted rules by impact.
