### ISSUE TITLE
PP New UI > View mode toggle :: Text is not changed from Expand all to Collapse all and vise versa depending on the current state.

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#124]
Steps:
1. Navigate to https://www.pageportrait.com/
2. Enter web page URL
3. On the landing page press toggle below the Sign in link on the upper right of the page
4. Select Expand all
5. Press toggle again

Actual: It still says "Expand all" and should be changed to "Collapse all" and vise versa.

**Comment by deadproxor** [comment]
Expand/Collapse All should be enabled before, if it's possible (_see "disabled" attribute_).

![screen shot 2016-07-20 at 10 43 35](https://cloud.githubusercontent.com/assets/1135832/16978914/10a2a9ec-4e67-11e6-966b-f67a5bff3214.png)
