### ISSUE TITLE
Normalize url 

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#25]
As an enhancement, it would be nice to have nice looking URL's in the browser. 
**Current:** https://www.pageportrait.com/portrait/?url=http%3A%2F%2Fwww.wedonweb.com
**Proposed:** https://www.pageportrait.com/portrait/wedonweb.com

**Comment by vpodk** [comment]
This is not useful for long URLs like "http://www.scalr.com/lp3/schedule-a-demo?__hssc=51282166.31.1453284408413&__hstc=51282166.58de062cdbdef7cf931c8fa6e9d788b2.1441532658819.1453229962049.1453284408413.245&__hsfp=&hsCtaTracking=6d33b157-8854-4e2e-8aeb-3c028e530e1b%7C5a635d2a-a3c7-402d-a487-089d1ad7604e".
