### ISSUE TITLE
Page metric: Micro formats

### ISSUE THREAD

**Issue by vpodk** [PagePortrait/Report#39]
Designed for humans first and machines second, microformats are a set of simple, open data formats built upon existing and widely adopted standards.
- http://microformats.org/wiki/Main_Page
- https://schema.org/docs/gs.html
- https://developers.google.com/structured-data
- https://www.w3.org/wiki/HTML_Data_Vocabularies

**Comment by ppokyd** [comment]
https://developers.google.com/structured-data/testing-tool/

**Comment by vpodk** [comment]
Thank you @ppokyd.  Initial version was deployed to www.pageportrait.com
Wiki page: https://github.com/PagePortrait/Report/wiki/Microdata
All found bugs or suggestion please post as new issue.
