### ISSUE TITLE
Button title partly hidden on Nexus 5X, Nexus 6P and iPhone 6 Plus.

### ISSUE THREAD

**Issue by fifi2dz** [PagePortrait/Report#47]
For those devices better to show button with arrow (like for iPhone 6) instead of button with text.
![pageportrait](https://cloud.githubusercontent.com/assets/18279522/14306577/4079e618-fb7d-11e5-8ac1-0cdf390153ea.png)

**Comment by vpodk** [comment]
Fixed and deployed to www.pageportrait.com
Thanks to @fifi2dz and @deadproxor for fast fix.
