### ISSUE TITLE
The image is not showing in Facebook sharing preview. 

### ISSUE THREAD

**Issue by fifi2dz** [PagePortrait/Report#51]
1. Open URL:     "  http://www.amazon.com/gp/product/B00IOY8XWQ/ref=s9_acss_bw_cg_odsbnc_1c1?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=13QQ37GM2FGFHMBACCSQ&pf_rd_t=101&pf_rd_p=d1464e5b-9823-422b-b438-84429fd170ba&pf_rd_i=6669702011   '' on Page Portrait. 
2. Scroll the page.
3. Check preview.
   Additional pictures below.

**Comment by fifi2dz** [comment]
![3](https://cloud.githubusercontent.com/assets/18279522/14554674/4d6e21f4-02a3-11e6-8c39-95ba04cff54b.png)
![2016-04-14_2320](https://cloud.githubusercontent.com/assets/18279522/14554682/5770d084-02a3-11e6-8365-a705d659ab07.png)
![pageportrait 2](https://cloud.githubusercontent.com/assets/18279522/14554691/61d4a8ca-02a3-11e6-8a95-2d081f5e1345.png)

**Comment by vpodk** [comment]
Seems the Amazon generates special image for social networks which does not present on page:

http://ecx.images-amazon.com/images/I/51CtmBFO6uL._SR600%2c315_PIWhiteStrip%2cBottomLeft%2c0%2c35_PIAmznPrime%2cBottomLeft%2c0%2c-5_PIStarRatingFOURANDHALF%2cBottomLeft%2c360%2c-6_SR600%2c315_ZA(16586%20Reviews)%2c445%2c286%2c400%2c400%2carial%2c12%2c4%2c0%2c0%2c5_SCLZZZZZZZ_.jpg

We can try to emulate similar behavior in future.
