### ISSUE TITLE
Amazon returns "Robot Check", instead of image and page data.

### ISSUE THREAD

**Issue by fifi2dz** [PagePortrait/Report#52]
1. Open URL: " http://www.amazon.com/gp/product/B00IOY8XWQ/ref=s9_acss_bw_cg_odsbnc_1c1?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=13QQ37GM2FGFHMBACCSQ&pf_rd_t=101&pf_rd_p=d1464e5b-9823-422b-b438-84429fd170ba&pf_rd_i=6669702011 '' on Page Portrait.
2. Scroll the page.
3. Check preview. 
4. Click one more time on "Discover"  button. 
5. Check preview again. 
   ![4](https://cloud.githubusercontent.com/assets/18279522/14555306/985a52d4-02a6-11e6-86b8-9e39d7e4c7b9.png)
   ![5](https://cloud.githubusercontent.com/assets/18279522/14555312/a2d54d5e-02a6-11e6-9835-54d703fccd41.png)

**Comment by vpodk** [comment]
Not actual.
