### ISSUE TITLE
The image is not showing in Facebook sharing preview (another example).

### ISSUE THREAD

**Issue by fifi2dz** [PagePortrait/Report#53]
1. Open URL: " http://www.biography.com/people/martin-luther-king-jr-9365086'' on Page Portrait.
2. Scroll the page.
3. Check preview.
   ![2016-04-15_1210-1](https://cloud.githubusercontent.com/assets/18279522/14572706/14cb88d4-0305-11e6-8999-8c105f60edb6.png)
   ![2016-04-15_1212-2](https://cloud.githubusercontent.com/assets/18279522/14572717/1ed9f28e-0305-11e6-81ea-7382071ae179.png)

**Comment by vpodk** [comment]
Not actual.
