### ISSUE TITLE
Plaintext Emails

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#60]
Similar to [Page Analytics](https://www.dtm.io/page-analytics/analyze/#module=server-security&q=http%253A%252F%252Firvo.net):
Check your webpage for plaintext email addresses. Any e-mail address posted in public is likely to be automatically collected by computer software used by bulk emailers (a process known as e-mail address harvesting). A spam harvester can read through the pages in your site and extract email addresses which are then added to bulk marketing databases and the result is more spam in your inbox.

**Comment by vpodk** [comment]
Latest changes are deployed to https://www.pageportrait.com
