### ISSUE TITLE
IP Canonicalization

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#62]
Similar to [Page Analytics](https://www.dtm.io/page-analytics/analyze/#module=server-security&q=dtm.io):
Test web resource for potential IP canonicalization issue. Canonicalization describes how a site can use slightly different URLs for the same page (for example, if site's IP address and domain name display the same page but do not resolve to the same URL). If this happens, search engines may be unsure as to which URL is the correct one to index and could cause duplicate content problems.

**Comment by vpodk** [comment]
Related:
- #38 (Page metric: URL Canonicalization)
- #93 (Merge URL Canonicalization and IP into one widget)
