### ISSUE TITLE
Deprecated HTML Tags Checker

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#64]
Deprecated HTML Tags Checker is needed to detect whether webpage uses some old HTML tags as those may be not supported in modern browsers.

**Comment by zalesky** [comment]
Also there are deprecated attributes for HTML Tags

**Comment by vpodk** [comment]
![screen shot 2016-06-13 at 12 38 09](https://cloud.githubusercontent.com/assets/11623226/16003101/b91d0a7a-3163-11e6-911b-19e9d3f22050.png)

Thanks to @AlbaMontis. Initial version was deployed to https://www.pageportrait.com
