### ISSUE TITLE
Media Query Techniques Checker

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#66]
Media Query Techniques Checker is intended to verify whether user's webpage uses media query techniques as this is guaranty of responsive design functionalities.

**Comment by vpodk** [comment]
![screen shot 2016-06-19 at 18 00 07](https://cloud.githubusercontent.com/assets/11623226/16178076/b8ee9ddc-3647-11e6-9194-a1e4bdefedca.png)

Deployed to https://www.pageportrait.com
