### ISSUE TITLE
Rule Section :: Long numbers are splitted to the next line

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#68]
URL to reproduce: http://amik.ru 
See attached screenshot below:
![screen shot 2016-05-17 at 11 24 27 am](https://cloud.githubusercontent.com/assets/18569728/15315782/56b39e9a-1c22-11e6-8933-1e6fc1749110.png)

**Comment by vpodk** [comment]
![screen shot 2016-06-13 at 13 15 08](https://cloud.githubusercontent.com/assets/11623226/16004188/e44b1a52-3168-11e6-9e66-27cea23fec94.png)

**Comment by vpodk** [comment]
Fixed and deployed to https://www.pageportrait.com. Thank to @deadproxor.
