### ISSUE TITLE
URL SEO Optimization

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#72]
Similar to [Page Analytics](https://www.dtm.io/page-analytics/analyze/#module=common-seo-issues&q=http%253A%252F%252Fkelta.ua).

**Comment by vpodk** [comment]
![screen shot 2016-06-13 at 12 20 27](https://cloud.githubusercontent.com/assets/11623226/16002600/4395c85c-3161-11e6-86a8-4f991e628af4.png)

Deployed to https://www.pageportrait.com
