### ISSUE TITLE
PP New UI :: To add missing icons

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#91]

**Comment by vpodk** [comment]
![screen shot 2016-06-13 at 14 21 54](https://cloud.githubusercontent.com/assets/11623226/16005876/5284438c-3172-11e6-95ad-1407fb175ddb.png)
![screen shot 2016-06-13 at 14 21 49](https://cloud.githubusercontent.com/assets/11623226/16005877/529990a2-3172-11e6-877b-d562f55f3d60.png)

**Comment by vpodk** [comment]
Updated and deployed to https://www.pageportrait.com
