### ISSUE TITLE
PP New UI :: Shifting and misalignment on mobile devices

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#98]
See attached screenshots below.
![screenshot_2016-06-10-22-31-17](https://cloud.githubusercontent.com/assets/18569728/16000218/ab483a7e-3153-11e6-9b50-1836327643ec.png)
![screenshot_2016-06-10-22-31-53](https://cloud.githubusercontent.com/assets/18569728/16000221/ab49fba2-3153-11e6-9210-2893ee037747.png)
![screenshot_2016-06-10-22-32-17](https://cloud.githubusercontent.com/assets/18569728/16000219/ab48d4ac-3153-11e6-8486-50941a1b4002.png)
![screenshot_2016-06-10-22-33-24](https://cloud.githubusercontent.com/assets/18569728/16000220/ab494662-3153-11e6-9d5b-8886e39d539f.png)
![screenshot_2016-06-10-22-33-36](https://cloud.githubusercontent.com/assets/18569728/16000217/ab48057c-3153-11e6-9e37-9abc4e0d1854.png)
![screenshot_2016-06-10-22-33-55](https://cloud.githubusercontent.com/assets/18569728/16000216/ab47ec40-3153-11e6-8cf9-5cafdefb5db3.png)
![screenshot_2016-06-10-22-35-01](https://cloud.githubusercontent.com/assets/18569728/16000223/ab7874dc-3153-11e6-99c9-f1bac580d661.png)
![screenshot_2016-06-12-11-43-53](https://cloud.githubusercontent.com/assets/18569728/16000224/ab7b0882-3153-11e6-829c-bc0fc8d46046.png)
![screenshot_2016-06-12-11-44-07](https://cloud.githubusercontent.com/assets/18569728/16000222/ab785326-3153-11e6-84e0-58b60ef25b86.png)

**Comment by vpodk** [comment]
@deadproxor Please split this issue to:
- Table related issues;
- Home page related issues;
- Social widgets related issues;
- Other issues if any.

**Comment by vpodk** [comment]
Splitted to:
- #107 (PP New UI :: Home page related issues)
- #109 (PP New UI :: Table related issues)
- #110 (PP New UI :: Social widgets related issues)
