### ISSUE TITLE
PP New UI :: Issue with charts on window resize

### ISSUE THREAD

**Issue by ghost** [PagePortrait/Report#99]

**Comment by vpodk** [comment]
Before resize:
![screen shot 2016-06-13 at 12 29 22](https://cloud.githubusercontent.com/assets/11623226/16002879/881451d2-3162-11e6-846c-f5d48e68838d.png)

After resize:
![screen shot 2016-06-13 at 12 29 37](https://cloud.githubusercontent.com/assets/11623226/16002880/8818e4ae-3162-11e6-8a77-50f35fa59ffd.png)

**Comment by vpodk** [comment]
Fixed and deployed to https://www.pageportrait.com
